#!/bin/sh

test -x /usr/sbin/update-pepperflashplugin-nonfree && /usr/sbin/update-pepperflashplugin-nonfree --status | grep -o ": [[:digit:]]*.[[:digit:]]*.[[:digit:]]*.[[:digit:]]*" | {
  read installed
  read available

  if [ "$installed" \< "$available" ] ; then
    /usr/sbin/update-pepperflashplugin-nonfree --install --quiet && echo "$(date) Updating pepperflash successful" >> /var/log/pepperupdate.log || echo "$(date) Updating pepperflash failed" >> /var/log/pepperupdate.log
  fi
}
