#!/bin/bash

mkdir -p /opt/pdfstudio/lib/tess/tessdata/
cd /opt/pdfstudio/lib/tess/tessdata/

wget http://download.qoppa.com/pdfstudio/ocr/languages11.xml

for LANGUAGE_FILE in deu fra eng spa; do
  grep -o "$LANGUAGE_FILE".tar.gz languages11.xml
done

