#!/bin/bash -e

## Copy facter to facter directory
cp /etc/puppet/manifests/files/usr/lib/ruby/vendor_ruby/facter/wireless_vendor.rb /usr/lib/ruby/vendor_ruby/facter/wireless_vendor.rb
cp /etc/puppet/manifests/files/usr/lib/ruby/vendor_ruby/facter/network_vendor.rb /usr/lib/ruby/vendor_ruby/facter/network_vendor.rb

#install package apt-transport-https
puppet apply -e 'Package { "apt-transport-https": ensure => installed }'

## Run Puppet locally using puppet apply
/usr/bin/puppet apply /etc/puppet/manifests/site.pp
PUPPET_EXIT=$?

## Run dconf to lock gnome preferences
dconf update

## Log status of the Puppet run
if [ $PUPPET_EXIT -eq 0 ]
then
    /usr/bin/logger -i "Puppet has run successfully" -t "puppet-run"
    exit 0
else
    /usr/bin/logger -i "Puppet has ran into an error, please run Puppet manually" -t "puppet-run"
    exit 1
fi

