#!/bin/bash -e

## Copy facter to facter directory
#cp -u /etc/puppet/manifests/files/usr/lib/ruby/vendor_ruby/facter/wireless_vendor.rb /usr/lib/ruby/vendor_ruby/facter/wireless_vendor.rb
#cp -u /etc/puppet/manifests/files/usr/lib/ruby/vendor_ruby/facter/network_vendor.rb /usr/lib/ruby/vendor_ruby/facter/network_vendor.rb
#cp -u /etc/puppet/manifests/files/usr/lib/ruby/vendor_ruby/facter/graphic_chipset.rb /usr/lib/ruby/vendor_ruby/facter/graphic_chipset.rb
#cp -u /etc/puppet/manifests/files/usr/lib/ruby/vendor_ruby/facter/network_r8168.rb /usr/lib/ruby/vendor_ruby/facter/network_r8168.rb

#install package apt-transport-https
#puppet apply -e 'Package { "apt-transport-https": ensure => installed }'
/usr/bin/puppet apply /etc/puppet/manifests/init.pp

## Run Puppet locally using puppet apply
/usr/bin/puppet apply /etc/puppet/manifests/site.pp
PUPPET_EXIT=$?

## Run dconf to lock gnome preferences
dconf update

## Log status of the Puppet run
if [ $PUPPET_EXIT -eq 0 ]
then
    /usr/bin/logger -i "Puppet has run successfully" -t "puppet-run"
    exit 0
else
    /usr/bin/logger -i "Puppet has ran into an error, please run Puppet manually" -t "puppet-run"
    exit 1
fi

